apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-2048-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules:
  - host: myservicea.kevinsha007.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-2048
            port:
              number: 80